### ISSUE TITLE
Korean version of README.md needs update with new nimbix setup.

### ISSUE THREAD

**Issue by markstur** [IBM/powerai-transfer-learning#15]
@changwoojung can you update? Should we remove the current one in the meantime?

**Comment by markstur** [comment]
There's a new PR #20 that also affects the README (not as important, but would be nice to sync).

**Comment by markstur** [comment]
maybe @hjjo can help with this?  Not sure if @changwoojung is available.

**Comment by hjjo** [comment]
@markstur I will be out of office until next Monday. If it's critical change, you can remove it until I come back or @changwoojung update it :-)

**Comment by stevemart** [comment]
Closed via #22
